# fly.toml app configuration file generated for hotplants on 2025-11-03T15:52:40-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hotplants'
primary_region = 'sjc'

[build]

[[services]]
  internal_port = 80
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]




[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
