/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a location from a textual description or address
         * @description The search API allows you to look up a location from a textual description or address. Nominatim supports structured and free-form search queries. The search query may also contain special phrases which are translated into specific OpenStreetMap (OSM) tags. This can be used to narrow down the kind of objects to be returned.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OSMGeocodeJson: {
            address?: {
                country?: string;
                province?: string;
                state?: string;
            };
            geotext?: string;
            display_name?: string;
            lat?: number;
            lon?: number;
            boundingbox?: number[];
        }[];
        StatusResponse: {
            /** @example [
             *       0,
             *       700
             *     ] */
            status: number;
            /** @example [
             *       "OK",
             *       "Database connection failed"
             *     ] */
            message: string;
            /** Format: date-time */
            data_updated?: string;
            /** @description A semver.org compliant version number (see https://semver.org). */
            software_version?: string;
            database_version?: components["schemas"]["StatusResponse"]["software_version"];
        };
        DetailsResponse: {
            place_id?: number;
            parent_place_id?: number;
            osm_type?: components["schemas"]["OSMType"];
            osm_id?: number;
            category?: string;
            type?: string;
            admin_level?: number;
            localname?: string;
            names?: {
                name?: string;
            };
            addresstags?: Record<string, never>;
            calculated_postcode?: string;
            country_code?: string;
            /** Format: date-time */
            indexed_date?: string;
            importance?: number;
            calculated_importance?: number;
            extratags?: Record<string, never>;
            rank_address?: number;
            rank_search?: number;
            isarea?: boolean;
            /** GeoJSON Point */
            centroid?: {
                /** @enum {string} */
                type: "Point";
                coordinates: number[];
                boundingbox?: number[];
            };
            /** GeoJSON */
            geometry?: {
                /** @enum {string} */
                type: "Point";
                coordinates: number[];
                boundingbox?: number[];
            } | {
                /** @enum {string} */
                type: "LineString";
                coordinates: number[][];
                boundingbox?: number[];
            } | {
                /** @enum {string} */
                type: "Polygon";
                coordinates: number[][][];
                boundingbox?: number[];
            } | {
                /** @enum {string} */
                type: "MultiPoint";
                coordinates: number[][];
                boundingbox?: number[];
            } | {
                /** @enum {string} */
                type: "MultiLineString";
                coordinates: number[][][];
                boundingbox?: number[];
            } | {
                /** @enum {string} */
                type: "MultiPolygon";
                coordinates: number[][][][];
                boundingbox?: number[];
            } | {
                /** @enum {string} */
                type: "GeometryCollection";
                geometries: ({
                    /** @enum {string} */
                    type: "Point";
                    coordinates: number[];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "LineString";
                    coordinates: number[][];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "Polygon";
                    coordinates: number[][][];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "MultiPoint";
                    coordinates: number[][];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "MultiLineString";
                    coordinates: number[][][];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "MultiPolygon";
                    coordinates: number[][][][];
                    boundingbox?: number[];
                })[];
                boundingbox?: number[];
            } | {
                /** @enum {string} */
                type: "Feature";
                id?: number | string;
                properties: null | Record<string, never>;
                geometry: null | {
                    /** @enum {string} */
                    type: "Point";
                    coordinates: number[];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "LineString";
                    coordinates: number[][];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "Polygon";
                    coordinates: number[][][];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "MultiPoint";
                    coordinates: number[][];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "MultiLineString";
                    coordinates: number[][][];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "MultiPolygon";
                    coordinates: number[][][][];
                    boundingbox?: number[];
                } | {
                    /** @enum {string} */
                    type: "GeometryCollection";
                    geometries: ({
                        /** @enum {string} */
                        type: "Point";
                        coordinates: number[];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "LineString";
                        coordinates: number[][];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "Polygon";
                        coordinates: number[][][];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "MultiPoint";
                        coordinates: number[][];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "MultiLineString";
                        coordinates: number[][][];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "MultiPolygon";
                        coordinates: number[][][][];
                        boundingbox?: number[];
                    })[];
                    boundingbox?: number[];
                };
                boundingbox?: number[];
            } | {
                /** @enum {string} */
                type: "FeatureCollection";
                features: {
                    /** @enum {string} */
                    type: "Feature";
                    id?: number | string;
                    properties: null | Record<string, never>;
                    geometry: null | {
                        /** @enum {string} */
                        type: "Point";
                        coordinates: number[];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "LineString";
                        coordinates: number[][];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "Polygon";
                        coordinates: number[][][];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "MultiPoint";
                        coordinates: number[][];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "MultiLineString";
                        coordinates: number[][][];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "MultiPolygon";
                        coordinates: number[][][][];
                        boundingbox?: number[];
                    } | {
                        /** @enum {string} */
                        type: "GeometryCollection";
                        geometries: ({
                            /** @enum {string} */
                            type: "Point";
                            coordinates: number[];
                            boundingbox?: number[];
                        } | {
                            /** @enum {string} */
                            type: "LineString";
                            coordinates: number[][];
                            boundingbox?: number[];
                        } | {
                            /** @enum {string} */
                            type: "Polygon";
                            coordinates: number[][][];
                            boundingbox?: number[];
                        } | {
                            /** @enum {string} */
                            type: "MultiPoint";
                            coordinates: number[][];
                            boundingbox?: number[];
                        } | {
                            /** @enum {string} */
                            type: "MultiLineString";
                            coordinates: number[][][];
                            boundingbox?: number[];
                        } | {
                            /** @enum {string} */
                            type: "MultiPolygon";
                            coordinates: number[][][][];
                            boundingbox?: number[];
                        })[];
                        boundingbox?: number[];
                    };
                    boundingbox?: number[];
                }[];
                boundingbox?: number[];
            };
            address?: {
                localname?: string;
                place_id?: number;
                osm_id?: number;
                osm_type?: components["schemas"]["OSMType"];
                class?: string;
                type?: string;
                admin_level?: number;
                rank_address?: number;
                distance?: number;
                isaddress?: boolean;
            }[];
        };
        ErrorResponse: {
            code?: number;
            message?: string;
        };
        /** @enum {string} */
        OSMType: "N" | "W" | "R";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query?: {
                /** @description Free-form query string to search for. Free-form queries are processed first left-to-right and then right-to-left if that fails. Commas are optional, but improve performance by reducing the complexity of the search. The free-form may also contain special phrases to describe the type of place to be returned or a coordinate to search close to a position. */
                q?: string;
                /** @description Name and/or type of POI. Do not combine with `q=<query>` parameter. */
                amenity?: string;
                /** @description Name of street with optional housenumber. Do not combine with `q=<query>` parameter. */
                street?: string;
                /** @description Name of city. Do not combine with `q=<query>` parameter. */
                city?: string;
                /** @description Name of county. Do not combine with `q=<query>` parameter. */
                county?: string;
                /** @description Name of state. Do not combine with `q=<query>` parameter. */
                state?: string;
                /** @description Name of country. Do not combine with `q=<query>` parameter. */
                country?: string;
                /** @description Postal code. Do not combine with `q=<query>` parameter. */
                postalcode?: string;
                /** @description Format of response. See [Place Output Formats](https://nominatim.org/release-docs/develop/api/Output/) for details on each format. If not specified, it is equal to `jsonv2`. */
                format?: "xml" | "json" | "jsonv2" | "geojson" | "geocodejson";
                /** @description Wrap JSON output in a callback function (JSONP) i.e. <string>(<json>). Only has an effect for JSON output formats. */
                json_callback?: string;
                /** @description Limit the maximum number of returned results. Nominatim may decide to return less results than given, if additional results do not sufficiently match the query. If not specified, it is equal to `10`. */
                limit?: number;
                /** @description Include a breakdown of the address into elements. If not specified, it is equal to `0`. */
                addressdetails?: number;
                /** @description Include additional information in the result if available, e.g. wikipedia link, opening hours. If not specified, it is equal to `0`. */
                extratags?: number;
                /** @description Include a full list of names for the result. These may include language variants, older names, references and brand. If not specified, it is equal to `0`. */
                namedetails?: number;
                /** @description Preferred language order for showing search results. This may either be a simple comma-separated list of language codes or have the same format as the [Accept-Language HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language). If not specified, it is equal to the content of Accept-Language HTTP header (browsers send the currently chosen browser language, command-line tools usually don't send any Accept-Language header). */
                "accept-language"?: string;
                /** @description Limit search results to one or more countries. The country code must be the [ISO 3166-1alpha2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code of the country, e.g. gb for the United Kingdom, de for Germany. Each place in Nominatim is assigned to one country code based on OSM country boundaries. In rare cases a place may not be in any country at all, for example, when it is in international waters. These places are also excluded when the filter is set. */
                countrycodes?: string;
                /** @description The layer filter allows to select places by themes, a comma-separated list of `address` (all places that make up an address: address points with house numbers, streets, inhabited places like suburbs, villages, cities, states, and administrative boundaries), `poi` (all points of interest like restaurants, shops, hotels but also less obvious features like recycling bins, guideposts or benches), `railway` (infrastructures like tracks), `natural` (feautures like rivers, lakes and mountains), `manmade` (catch-all for features not covered by the other layers). */
                layer?: string;
                /** @description The featureType allows to have a more fine-grained selection for places from the address layer. Results can be restricted to places that make up the 'state', 'country' or 'city' part of an address. A featureType of settlement selects any human inhabited feature from 'state' down to 'neighbourhood'. If not specified, results are automatically restricted to the address layer. */
                featureType?: "country" | "state" | "city" | "settlement";
                /** @description If you do not want certain OSM objects to appear in the search result, give a comma separated list of the `place_ids` you want to skip. This can be used to retrieve additional search results. For example, if a previous query only returned a few results, then including those here would cause the search to return other, less accurate, matches (if possible). */
                exclude_place_ids?: string;
                /** @description The preferred area to find search results. Any two corner points of the box are accepted as long as they span a real box. In `viewbox=<x1>,<y1>,<x2>,<y2>` x is longitude, y is latitude. */
                viewbox?: string;
                /** @description When a viewbox is given, restrict the result to items contained within that viewbox (see above). When `viewbox` and `bounded=1` are given, an amenity only search is allowed. Give the special keyword for the amenity in square brackets, e.g. `[pub]` and a selection of objects of this type is returned. There is no guarantee that the result is complete. */
                bounded?: number;
                /** @description Output geometry of results as a GeoJSON. */
                polygon_geojson?: number;
                /** @description Output geometry of results as a KML. */
                polygon_kml?: number;
                /** @description Output geometry of results as a SVG. */
                polygon_svg?: number;
                /** @description Output geometry of results as a WKT. */
                polygon_text?: number;
                /** @description When one of the polygon_* outputs is chosen, return a simplified version of the output geometry. The parameter is the tolerance in degrees with which the geometry may differ from the original geometry. Topology is preserved in the result. */
                polygon_threshold?: number;
                /** @description If you are making large numbers of request please include an appropriate email address to identify your requests. See Nominatim's [Usage Policy](https://operations.osmfoundation.org/policies/nominatim/) for more details. */
                email?: string;
                /** @description Sometimes you have several objects in OSM identifying the same place or object in reality. The simplest case is a street being split into many different OSM ways due to different characteristics. Nominatim will attempt to detect such duplicates and only return one match unless this parameter is set to 0. If not specified, it is equal to `0`. */
                dedupe?: number;
                /** @description Output assorted developer debug information. Data on internals of Nominatim's Search Loop logic, and SQL queries. The output is (rough) HTML format. This overrides the specified machine readable format. If not specified, it is equal to `0`. */
                debug?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OSMGeocodeJson"];
                };
            };
        };
    };
}
